debug: true
logging:
  level:
    root: debug
spring:
  jpa:
    database: H2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.driver
    url: jdbc:h2:mem:${db-name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  liquibase:
    enabled: false