spring:
  profiles:
    active: "@activatedProperties@"
  application:
    name: "${artifactId}"
    version: ${version}
  messages:
    basename: i18n/messages
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${db-name}?currentSchema=${db-schema}
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml
    default-schema: ${db-schema}
server:
  port: ${backend-port}
