version: "3.8"

services: 
    cache:
        image: redis:latest
        container_name: cache
        env_file: env
        ports: 
            - 6379:6379
        networks:
            - backend
    db:
        image: postgres:latest
        container_name: db
        env_file: env
        ports: 
            - 5432:5432
        networks:
            - backend
    backend:
        image: ${artifactId}:latest
        build: .
        container_name: backend
        env_file: env
        ports: 
            - ${backend-port}:${backend-port}
        networks:
            - backend
networks: 
    backend:
        external: true
        name: backend